### ISSUE TITLE
Unauthorized access

### ISSUE THREAD

**Issue by BhumikaShah39** [pranjalipudasaini/Farmish#7]
Cart can be accessed by non-registered users.

**Comment by pranjalipudasaini** [comment]
This bug has been fixed by simply adding a login_required decorator from django.contrib.auth.decorators which checks whether the user is logged in or not before giving them access to certain pages.
![Screenshot 2024-04-20 151330](https://github.com/pranjalipudasaini/Farmish/assets/119116985/8fe94a46-bbfb-45b7-964c-f356b77119e8)
